version: '3.4'

services:
  backend:
    env_file: environment.env
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - '3000:3000'
    depends_on:
      - db

  db:
    env_file: environment.env
    image: postgres:11.14-alpine
    volumes:
      - mediumclone:/var/lib/postgresql/data/
    ports:
      - '5432:5432'

volumes:
  mediumclone:
